title = "BetterUI Interface"
gitRepoUrl = "https://github.com/easyontop/BetterUI"
gitSourceBranch = "master"
changelog = true

classOrder = []

[docsusaurus]
organizationName = "SnwJS Development"
projectName = "BetterUI Interface"
deploymentBranch = "gh-pages"
tagline = "The advanced UI creator"
titleDelimiter = "•"

url = "https://easyontop.github.io"
baseUrl = "/BetterUI"

[home]
enabled = true
includeReadme = false

[[navbar.items]]
href = "/api"
label = "API Reference"
position = "right"

[[navbar.items]]
href = "/docs/intro"
label = "Guide"
position = "right"

[[navbar.items]]
href = "https://discord.gg/fV3vBJVHAH"
label = "Discord"
position = "right"

[footer]
copyright = "Made by easyontop._. with ❣️"